/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Create Action with Condition client demonstrates adding the different types of conditions to an action of an existing zone 
 * using the 'request' node module.
 */
var request = require('request');

var percenatgeCrossedData =
{
    "security": {
    	/* The apiKey is generated when you create an application. */
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
        /* This key is generated by Bluedot Point Access UI when your account is created. It is also available
         * on the PointAccess interface in the Edit Profile section.*/        
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
        	/* The zoneId is the id of the zone being updated. This can be fetched by calling GET Zones API*/
            "zoneId": "722c991a-3ebb-4143-b441-5b0c0cf680a0",
            "actions": {
                "customActions": [
                    {
                        "name" : "A Custom Action with Percentage Crossed Condition",
                        "conditions": {
                            "percentageCrossed": [
                                {
                                    "percentage": 45,
                                    /* Time in Hour:Minute format.*/
                                    "timeoutPeriod": "00: 01"
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
};

var sequentialData =
{
    "security": {
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
            "zoneId": "722c991a-3ebb-4143-b441-5b0c0cf680a0",
            "actions": {
                "customActions": [
                    {
                    	"name": "A Custom Action with a Sequential Percentage Crossed Condition",
                        "conditions": {
                            "percentageCrossed": [
                                {
                                    "percentage": 45,
                                    /* Time in Hour:Minute format.*/
                                    "timeoutPeriod": "00: 01",
                                    "sequential": true
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
};

var dateRangeData =
{
    "security": {
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",   
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
            "zoneId": "722c991a-3ebb-4143-b441-5b0c0cf680a0",
            "actions": {
                "customActions": [
                    {
                    	"name": "A Custom Action with a Date Condition",
                        "conditions": {
                            "dateRange": [
                                {
                                    "start": "01/10/2016",
                                    "end": "01/12/2017"
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
};

var timeActiveData =
{
    "security": {
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
            "zoneId": "722c991a-3ebb-4143-b441-5b0c0cf680a0",
            "actions": {
                "customActions": [
                    {
                    	"name": "A Custom Action with a Time Condition",
                        "conditions": {
                        	"timeActive": [
                               {
                                   "from": {
                                	   /* Time in Hour:Minute format.*/
                                       "time": "10:00",
                                       "period": "am"
                                   },
                                   "to": {
                                	   /* Time in Hour:Minute format.*/
                                       "time": "02:00",
                                       "period": "pm"
                                   }
                               }
                           ]
                        }
                    }
                ]
            }
        }
    }
};

var bearingData =
{
    "security": {
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",    
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
            "zoneId": "722c991a-3ebb-4143-b441-5b0c0cf680a0",
            "actions": {
            	"customActions": [
                    {
                        "name": "A Custom Action with a Bearing Condition",
                        "conditions": {
                            "bearing": [
                                {
                                    "fromAngle": 80,
                                    "toAngle": 200
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
};

var speedData =
{
    "security": {
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",    
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
            "zoneId": "722c991a-3ebb-4143-b441-5b0c0cf680a0",
            "actions": {
            	"customActions": [
                    {
                        "name": "A Custom Action with a Speed Condition",
                        "conditions": {
                            "speed": [
                                {
                                    "minimumSpeed": 10,
                                    "maximumSpeed": 30
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
};

var options = {
    uri: 'https://api.bluedotinnovation.com/1/actions',
    method: 'POST',
    json: sequentialData
};
request(options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);