/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Delete Action client demonstrates deleting an action from an existing zone 
 * using the 'request' node module
 */
var request = require('request');
 
var bdCustomerApiKey = "6ab02370-97c4-11e4-b3f3-00155d53317c"; //This key is generated by Bluedot Point Access UI when your account is created.
var bdApplicationApiKey    = "d66d4f5d-7c09-4bd1-8549-48893f121"; //This apiKey is generated when you create an application.
var bdZoneId = "4f134aaa-3382-49bb-b7c7-a0bf72e56238";  //This is the ID of the zone being updated. This can be fetched by calling GET Zones API.
var bdActionId = "86bd13a8-d7da-4c92-afba-d000dc04b422"; //This is the ID of the action being deleted. This can be fetched by calling GET Zones API.
 
var options = {
    uri: "https://api.bluedotinnovation.com/1/actions?customerApiKey=" + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + 
    	"&zoneId=" + bdZoneId + "&actionId=" + bdActionId,
    method: "DELETE"
};
 
request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);