/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Create Application Zones Sync Enabled client demonstrates adding an application to your Bluedot backend 
 * using the 'request' node module for which the zones sync will be available using Firebase push.
 */

var request = require('request');

var applicationWithZonesSync = {
    "security": {
    	/* This key is generated by Bluedot Point Access UI when your account is created. It is also available
         * on the PointAccess interface in the Edit Profile section. */ 
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "application" : {
            "name" : "A Bluedot Application",
            "packageName": "au.com.bluedot.creationtest",
            /* Time in Hour:Minute format.*/
            "nextRuleUpdateIntervalFormatted": "00:07",
            /*The Web API key from Firebase project settings. 
			 * Using this key our backend will be able to communicate with Firebase to deliver the 
			 * zones that need to be synced to your application.*/
            "firebaseApiKey": "gDZyt1Bj_Y6S8BKyQfKH6uZ9wc475hrRlGA_6lS"
        }
    }
};

var options = {
    uri: 'https://api.bluedotinnovation.com/1/applications',
    method: 'POST',
    json: applicationWithZonesSync
};

request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);
