/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Delete Application client demonstrates deleting an application using 'request' node module.
 */
var request = require('request');
 
var bdCustomerApiKey = "6ab02370-97c4-11e4-b3f3-00155d53317c"; //This key is generated by Bluedot Point Access UI when your account is created.
var bdApplicationId = "29d0571f-cfb3-459f-a346-6e11a351ad31"; //This ID of the application being deleted and can be retrieved through the GET Applications call.
 
var options = {
    uri: "https://api.bluedotinnovation.com/1/applications?customerApiKey=" + bdCustomerApiKey+ "&applicationId=" + bdApplicationId,
    method: "DELETE"
};
 
request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);