/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Delete Beacon from Zone client demonstrates dissociating a beacon added to an existing zone 
 * using 'request' node module.
 */
var request = require('request');
 
var bdCustomerApiKey = "b2a9e860-2890-11e6-8148-0639e7649356"; //This key is generated by Bluedot Access UI when you register
var bdApplicationApiKey    = "38655d80-3774-11e6-9cb1-0639e7649356"; //This apiKey is generated when you create an application
var bdZoneId = "083ec47c-7785-45dd-8c59-eb7eef96acd7"; //This is the ID of the zone being updated. This can be retrieved through the GET Zones API.
var bdBeaconId = "09d04533-d421-449b-9fc1-84c89b3a34d1"; //Beacon ID generated when creating new beacons. This can be retrieved through the GET Beacons API.
 
var options = {
    uri: "https://api.bluedotinnovation.com/1/zones/beacons?customerApiKey=" + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + 
    	"&zoneId=" + bdZoneId + "&beaconId=" + bdBeaconId,
    method: "DELETE"
};
 
request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);