/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Get All Beacons client demonstrates listing all the beacons added to the customer's account from Bluedot backend 
 * using 'request' node module. 
 */

var request = require('request');
var bdCustomerApiKey = "7cd1ea80-d40e-11e4-84cb-b8ca3a6b879d"; //This key is generated by Bluedot Point Access UI when your account is created.
var options = {
    uri: 'https://api.bluedotinnovation.com/1/beacons?customerApiKey=' + bdCustomerApiKey,
    method: 'GET'
};
request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        var result = response.body;
        if( typeof result !== 'string' ) {
            console.log("Error in response");
            return;
            result = JSON.stringify(result)
        }
        console.log(result);
    }
);
