/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Get Beacon client demonstrates listing a beacon for a given beaconId for a customer's account from Bluedot backend  
 * using 'request' node module. 
 */

var request = require('request');
var bdCustomerApiKey = "7cd1ea80-d40e-11e4-84cb-b8ca3a6b879d"; //This key is generated by Bluedot Point Access UI when your account is created.
var bdBeaconId = "11146bf3-b894-4491-9ef1-4f151f782730"; // This is the ID of the beacon being retrieved. 
var options = {
    uri: 'https://apiuat2.bluedotinnovation.com/1/beacons?customerApiKey=' + bdCustomerApiKey + '&beaconId=' + bdBeaconId,
    method: 'GET'
};
request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        var result = response.body;
        if( typeof result !== 'string' ) {
            console.log("WTF");
            return;
            result = JSON.stringify(result)
        }
        console.log(result);
    }
);
