/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * CheckInActivity client demonstrates fetching checkIn activities for a given zone using the 'request' node module.
 * 100 Check-in activities are returned per call, increment the page number parameter to get records corresponding to the page
 * This API service also accepts a date range as parameter(optional) where records within the start date and the end date range are returned
 */
var request             = require('request');
var bdZoneId		    = '24d9a245-2087-421b-9972-2af2ee0970f1'; // This is the ID of the zone for which the check-in data is needed.
var bdCustomerApiKey    = "86577370-7b91-11e4-bcb7-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register
var bdApplicationApiKey = "86577370-7b91-11e4-bcb7-a0481cdc3311"; //This apiKey is generated when you create an application
var startDate           = "11/9/2014";
var endDate             = "14/9/2014";

//Increment the page number to get the next 100
//Example with Date
request.get ( 'https://api.bluedotinnovation.com/1/checkinactivities?simpleCheckInZoneId=' + bdZoneId + '&customerApiKey=' + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + 
				"&startdate="+ startDate + "&enddate=" + endDate + "&pagenumber=0",
    function (error, response)
    {
        if (error) {
            console.log(error);
        }
        var result = response.body;
        if( typeof result !== 'string' ) {
            console.log("WTF");
            return;
            result = JSON.stringify(result)
        }
        console.log(result);
    }
);