/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * CheckInActivity client demonstrates fetching checkIn activities for a given zone using the 'request' node module.
 * 100 Check-in activities are returned per call, increment the page number parameter to get records corresponding to the page
 * This API service also accepts a date range as parameter(optional) where records within the start date and the end date range are returned
 */
var request             = require('request');
var bdCustomerApiKey    = "b2a9e860-2890-11e6-8148-0639e7649356"; //This key is generated by Bluedot Point Access UI when your account is created.
var bdApplicationApiKey = "14163ef0-2891-11e6-8148-0639e7649356"; //This apiKey is generated when you create an application.
var bdZoneId		    = "c6814aba-d582-4b9e-8788-924f1a0a4c8a"; //This is the ID of the zone for which the check-in data is needed.
var receivedAtStart     = "2016-06-12";
var receivedAtEnd       = "2016-06-18";

//Increment the page number to get the next 100
//Example with Date
request.get ( 'https://api.bluedotinnovation.com/2/checkinactivities?customerApiKey=' + bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + 
				"&zoneId=" + bdZoneId  + "&receivedAtStart="+ receivedAtStart + "&receivedAtEnd=" + receivedAtEnd + "&pageNumber=0",
    function (error, response)
    {
        if (error) {
            console.log(error);
        }
        var result = response.body;
        if( typeof result !== 'string' ) {
            console.log("Error in response");
            return;
            result = JSON.stringify(result)
        }
        console.log(result);
    }e
);