/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Delete Fence client demonstrates deleting a fence using 'request' node module.
 */
var request = require('request');
 
var bdCustomerApiKey = "6ab02370-97c4-11e4-b3f3-00155d53317c"; //This key is generated by Bluedot Access UI when you register
var bdApplicationApiKey    = "d66d4f5d-7c09-4bd1-8549-48893f121"; //This apiKey is generated when you create an application
var bdZoneId = "4f134aaa-3382-49bb-b7c7-a0bf72e56238"; //This is the id of the zone being updated. This can be fetched by calling GET zones API
var bdFenceId = "916988ef-f0c1-45b8-a719-6dc4b401025e"; //This is the id of the fence being deleted. This can be fetched by calling GET zones API
 
var options = {
    uri: "https://api.bluedotinnovation.com/1/fences?customerApiKey="+ bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + 
    	"&zoneId=" + bdZoneId + "&fenceId=" + bdFenceId,
    method: "DELETE"
};
 
request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);