/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Create Complete Zone client demonstrates adding a complete zone which has fences, beacons and actions 
 * to an existing application using 'request' node module.
 */
var request = require('request');

//JSON for a complete Zone with a beacon and a custom action which is active for a certain time period during the day.  
//Time values have a format of HH:MM and the period value has to be one of {am/pm}
var zoneTimeActiveData =
	{
	    "security": {
	    	/* The apiKey is generated when you create an application. */
	        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
	        /* This key is generated by Bluedot Point Access UI when your account is created. It is also available
             * on the PointAccess interface in the Edit Profile section. */       
	        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
	    },
	    "content": {
	        "zone": {
	            "zoneName": "starbucks",
	            "minimumRetriggerTime": "00:01",
	            "enableCheckOut": false,
	            "timeActive": {
	                "from": {
	                    /* Time in Hour:Minute format.*/
	                    "time": "0:00",
	                    "period": "am"
	                },
	                "to": {
	                    /* Time in Hour:Minute format.*/
	                    "time": "12:00",
	                    "period": "pm"
	                }
	            },
	            "actions": {
	                "customActions": [
	                    {
	                        "name": "A Custom Application action"
	                    }
	                ]
	            },
	            "beacons": [
                    {
                    	/*This is the ID of a beacon registered to a customer's account, 
                    	 * which has to be associated with a zone.  */
                        "beaconId" : "f4d3c2f3-b2ba-4529-adac-18af1598ee4f",
                        "proximity" : 1,
                        "order": 1
                    }
                ]
	        }
	    }
	};
//JSON for a complete Zone which is active all day with a circular geofence and a message action.
var zoneActiveAllDayData =
{
    "security": {
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",     
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
            "zoneName": "starbucks",
            "minimumRetriggerTime": "00:01",
            "enableCheckOut": false,
            "activeAllDay": true,
            "fences": {
                "circles": [
                    {
                    	"order": 1
                        "name": "A circleur fence",
                        "color": "#000ffff",
                        "radius": 8.00,
                        "center": {
                            "latitude": -37.8159544565362,
                            "longitude": 144.9723565578461
                        }
                    }
                ]
            },
            "actions": {
                "messageActions": [
                    {
                        "name" : "A Message Action",
                        "title" : "Welcome to Bluedot Innovation",
                        "message" : "Welcome to Bluedot Innovation Offices"
                    }
                ]
            }
        }
    }
};

var options = {
    uri: 'https://api.bluedotinnovation.com/1/zones',
    method: 'POST',
    json: zoneTimeActiveData
};

request(options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);