/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Delete Zone client demonstrates deleting a zone using 'request' node module
 */
var request = require('request');
 
var bdCustomerApiKey = "6ab02370-97c4-11e4-b3f3-00155d53317c"; //This key is generated by Bluedot Point Access UI when your account is created.
var bdApplicationApiKey    = "d66d4f5d-7c09-4bd1-8549-48893f121"; //This apiKey is generated when you create an application
var bdZoneId = "e8ed5a00-705c-409a-8c1e-9e4f7c70bbd6"; //This is the id of the zone being deleted. This can be fetched by calling GET zones API
 
var options = {
    uri: "https://api.bluedotinnovation.com/1/zones?customerApiKey="+ bdCustomerApiKey + "&apiKey=" + bdApplicationApiKey + "&zoneId=" + bdZoneId,
    method: "DELETE"
};
 
request ( options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);