/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Get All Zones client demonstrates the listing of zone details for a given customer's application using 'request' node module.
 * 100 zones are returned per call, increment the page number parameter to get records corresponding to the page.
 */

var request  = require('request');


var  bdApplicationApiKey = 'c2c8211f-796f-4eda-b6ce-05467b5263a9'; //This apiKey is generated when you create an application
var  bdCustomerApiKey = '86577370-7b91-11e4-bcb7-a0481cdc3311'; //This key is generated by Bluedot Access UI when you register

request.get ( 'https://api.bluedotinnovation.com/1/zones?customerApiKey=' + bdCustomerApiKey + '&apiKey=' + bdApplicationApiKey + "&pageNumber=0",
    function (error, response) {
        if (error) {
            console.log(error);
        }
        var result = response.body;
        if( typeof result !== 'string' ) {
            console.log("WTF");
            return;
            result = JSON.stringify(result)
        }
        console.log(result);
    }
);
