/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Get Zone client demonstrates the listing of zone details for a given customer's zoneId using 'request' node module.
 */

var request  = require('request');

var bdCustomerApiKey  = '76e1ae30-c616-11e5-a7c0-b8ca3a6b879d'; //This key is generated by Bluedot Point Access UI when your account is created.
var bdApplicationApiKey = 'dee11930-ebff-11e5-8e27-bc305bf60831'; //This apiKey is generated when you create an application.
var bdZoneId = '67f99448-a646-43c9-a6ae-0d823d65edbd'; //This is the id of the zone being retrieved.

request.get ( 'https://api.bluedotinnovation.com/1/zones?customerApiKey=' + bdCustomerApiKey + '&apiKey=' + bdApplicationApiKey + "&zoneId=" + bdZoneId,
    function (error, response) {
        if (error) {
            console.log(error);
        }
        var result = response.body;
        if( typeof result !== 'string' ) {
            console.log("Error in response");
            return;
            result = JSON.stringify(result)
        }
        console.log(result);
    }
);
