/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * The Post Zones Sync client demonstrates how the zones/sync endpoint can be used to sync the newly created, updated or deleted zones to
 * all mobile devices using your application.
 */
var request = require('request');

var zonesDataSync =
	{
	    "security": {
	    	/* The apiKey is generated when you create an application. */
	        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
	        /* This key is generated by Bluedot Point Access UI when your account is created. It is also available
             * on the PointAccess interface in the Edit Profile section. */       
	        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
	    }
	};

var options = {
    uri: 'https://api.bluedotinnovation.com/1/zones/sync',
    method: 'POST',
    json: zonesDataSync
};

request(options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);