/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Post Geofeature Sequence client demonstrates zones/sequence endpoint can be used to sequence/order the geofeatures in a Zone
 * to be used for triggering the Sequential condition using 'request' node module.
 */
var request = require('request');

var geofeatureSequence =
	{
	    "security": {
	    	/* The apiKey is generated when you create an application. */
	        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
	        /* This key is generated by Bluedot Point Access UI when your account is created. It is also available
             * on the PointAccess interface in the Edit Profile section. */       
	        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
	    },
	    "content": {
	        "zone": {
	        	/* The zoneId is the id of the zone being updated. This can be fetched by calling GET zones API */
	            "zoneId": "a6375661-07e5-4596-800e-eef37d3cd6a6",
	            /*An ordered list of fence and beacon identifiers to be used for the Sequence condition.*/
	            "sequence": [
	                "fdf1a69b-090a-48f7-99d0-7eb631f22eac",
	                "fbe38318-9b71-410e-98cc-10c64cdb7be4"
	            ]
	        }
	    }
	};

var options = {
    uri: 'https://api.bluedotinnovation.com/1/zones/sequence',
    method: 'POST',
    json: geofeatureSequence
};

request(options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);