/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Update Complete Zone client demonstrates updating a complete zone which has fences, beacons and actions in a single request
 * to an existing application using 'request' node module.
 */
var request = require('request');

//JSON for a complete Zone with a beacon and a custom action which is active for a certain time period during the day.  
//Time values have a format of HH:MM and the period value has to be one of {am/pm}
var zoneTimeActiveData =
	{
	    "security": {
	    	/* The apiKey is generated when you create an application. */
	        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
	        /* This key is generated by Bluedot Point Access UI when your account is created. It is also available
             * on the PointAccess interface in the Edit Profile section. */       
	        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
	    },
	    "content": {
	        "zone": {
	        	/* The zoneId is the id of the zone being updated. This can be fetched by calling GET zones API */
	        	"zoneId":"cc6f9dd1-3d69-454d-abdd-58176cbf67dc",
	            "zoneName": "starbucks",
	            "minimumRetriggerTime": "00:01",
	            "enableCheckOut": false,
	            "timeActive": {
	                "from": {
	                    /* Time in Hour:Minute format.*/
	                    "time": "0:00",
	                    "period": "am"
	                },
	                "to": {
	                    /* Time in Hour:Minute format.*/
	                    "time": "12:00",
	                    "period": "pm"
	                }
	            },
	            "actions": {
	                "customActions": [
	                    {
	                    	/* The actionId is the id of the URL action being updated. 
                        	 * This can be fetched by calling zones/getAll API */
                            "actionId" : 'dc8209fc-9e92-4f81-8d4e-a96d52f99524',
                            "conditions": {
                                "percentageCrossed":
                                    [{
                                    	"percentage": 45,
                                    	/* Time in Hour:Minute format.*/
                                        "timeoutPeriod": "00:01"
                                    }],
                                "dateRange": [
                                    {
                                        "start": "12/12/2014",
                                        "end": "14/12/2014"
                                    }
                                ],
                                "timeActive": [{
                                    "from": {
                                        /* Time in Hour:Minute format.*/
                                        "time": "10:00",
                                        "period": "am"
                                    },
                                    "to": {
                                        /* Time in Hour:Minute format.*/
                                        "time": "2:00",
                                        "period": "pm"
                                    }
                                }]
                            }
	                    }
	                ]
	            },
	            "beacons": [
                    {
                    	/*This is the ID of a beacon registered to a customer's account, 
                    	 * which has to be associated with a zone.  */
                        "beaconId" : "f4d3c2f3-b2ba-4529-adac-18af1598ee4f",
                        "proximity" : 2
                    }
                ]
	        }
	    }
	};
//JSON for a complete Zone which is active all day with a circular geofence and a message action.
var zoneActiveAllDayData =
{
    "security": {
        "apiKey" : "c2c8211f-796f-4eda-b6ce-05467b5263a9",
        /*
         customerApiKey is generated when customer registers first time. It is also available
         on the PointAccess interface in the Edit Profile section.
         */        
        "customerApiKey": "86577370-7b91-11e4-bcb7-a0481cdc3311"
    },
    "content": {
        "zone": {
        	/* The zoneId is the id of the zone being updated. This can be fetched by calling GET zones API */
        	"zoneId":"cc6f9dd1-3d69-454d-abdd-58176cbf67dc",
            "zoneName": "starbucks",
            "minimumRetriggerTime": "00:01",
            "enableCheckOut": false,
            "activeAllDay": true,
            "fences": {
                "circles": [
                    {
                    	/* This is the id of the circular fence being updated. This can be fetched by calling the GET zones API */
                        "fenceId": '00f3f2af-bcdf-494e-a81c-481aff88f992',
                        "name": "A circleur fence",
                        "color": "#000ffff",
                        "radius": 8.00,
                        "center": {
                            "latitude": -37.8159544565362,
                            "longitude": 144.9723565578461
                        }
                    }
                ]
            },
            "actions": {
                "messageActions": [
                    {
                    	/* The actionId is the id of the message action being updated. 
                    	 * This can be fetched by calling zones/getAll API */
                        "actionId" : 'b83c7308-0191-4905-aac8-dc7dd8e609a3',
                        "title" : "Welcome to Bluedot Innovation",
                        "message" : "Welcome to Bluedot Innovation Offices"
                    }
                ]
            }
        }
    }
};

var options = {
    uri: 'https://api.bluedotinnovation.com/1/zones',
    method: 'POST',
    json: zoneTimeActiveData
};

request(options,
    function (error, response, body) {
        if (error) {
            console.log(error);
        }
        console.log(JSON.stringify(response.body));
    }
);